name: squadio_task
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:


  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^3.2.0
  http: ^0.13.3
  image_downloader: ^0.31.0
  equatable: ^2.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  internet_connection_checker: ^0.0.1+3
  get_it: ^7.2.0



dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/

